// Date: 4/6/2015 6:57:47 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.turkey.turkeyUtil.Armor;

import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

@SideOnly(Side.CLIENT)
public class ModelJedsWig extends ModelBiped
{
	
	public static ModelJedsWig modelWig = new ModelJedsWig();
	
	ModelRenderer wig;

	public ModelJedsWig()
	{
		super(0f, 0f, 128, 32);
		
		textureWidth = 128;
		textureHeight = 32;

		wig = new ModelRenderer(this, 56, 0);
		wig.addBox(-5.0F, -9.0F, -5.0F, 10, 17, 10);
		wig.setRotationPoint(0.0F, 0.0F , 0.0F);
		wig.setTextureSize(128, 32);
		wig.mirror = true;
		setRotation(wig, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		wig.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		wig.rotateAngleX = super.bipedHead.rotateAngleX;
		wig.rotateAngleY = super.bipedHead.rotateAngleY;
	}

}
